
// Action types....
import {mirrorKeys} from '../utilities';

export default mirrorKeys([
  'USER_ACCEPTED_TERMS',

  'PHONE_NUMBER_UPDATED',

  'SMS_VERIFICATION_SENT',
  'SMS_VERIFICATION_CODE_ENTERED',
  'SMS_VERIFICATION_CODE_ACCEPTED',
  'SMS_VERIFICATION_CODE_REJECTED',

  'PROFILE_UPDATED',

  'MAP_CREATED',
  'MAP_DELETED',
  'MAP_GPS_TOGGLED'
]);
